#!/bin/bash
if dpkg -s mollusc-themes |grep Status |grep -qi installed > /dev/null 2>&1; then
  version=$(dpkg -s mollusc-themes |grep "Version: ")
  version=${version//Version: }
else
  echo "Mollusc-themes not installed, please install and try again"
  exit
fi

updateYaru() {
  if [[ "$1" == "stock" ]]; then
    installYaru "stock"
    return
  elif [[ "$1" == "release" ]]; then
    installYaru "release"
    return
  elif [[ "$1" == "unstable" ]]; then
    read -r -p "Yaru will be updated to an unstable version. Are you sure? [y/N] " response
    if ! [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
      echo "Cancelled"
      exit
    fi
    installYaru "unstable"
    return
  elif [[ "$1" == "setup" ]]; then
    installYaru "setup"
    return
  else
    echo "No mode set, run again with one of 'stock', 'release', 'unstable' or 'setup'"
  fi
}

installYaru() {
  cd /usr/share/mollusc-themes/
  if [[ "$1" != "setup" ]]; then
    echo "Installing yaru:"
  else
    echo "Setting up yaru..."
  fi

  if [[ "$1" == "stock" ]]; then
    yaruPackage=$(ls ./ |grep yaru*.tar.gz)
    yaruDir=${yaruPackage//.tar.gz}
    sudo tar -xf "$yaruPackage"
  elif [[ "$1" == "release" ]]; then
    #Check for connection
    #Download latest version .tar.gz
    #Set yaruDir
    #Extract files

    #Remove
    return
  elif [[ "$1" == "unstable" ]]; then
    yaruDir="yaru"
    sudo git clone https://github.com/ubuntu/yaru.git
  elif [[ "$1" == "setup" ]]; then
    if gsettings list-schemas |grep user-theme > /dev/null 2>&1; then
      gsettings set org.gnome.shell.extensions.user-theme name Yaru-dark
    else
      schemasPath=$(find / -iname 'gschemas.compiled' 2>&1 |grep -v "Permission denied" |grep user-theme@gnome-shell-extensions.gcampax.github.com)
      if [[ "$schemasPath" == "" ]]; then
        echo "User-themes not installed correctly, or an error occured"
        return
      fi
      gsettings --schemadir "${schemasPath///gschemas.compiled}" set org.gnome.shell.extensions.user-theme name Yaru-dark
    fi

    gsettings set org.gnome.desktop.interface gtk-theme Yaru-dark
    gsettings set org.gnome.desktop.interface icon-theme Yaru
    gsettings set org.gnome.desktop.sound theme-name Yaru
    gsettings set org.gnome.desktop.interface cursor-theme Yaru
  fi

  if [[ -d "/usr/share/mollusc-themes/$yaruDir" ]] && [[ "$1" != "setup" ]]; then
    cd "$yaruDir"
    sudo meson build
    cd build
    sudo rm -rf /usr/share/themes/Yaru*
    sudo ninja install
    cd ../../
    sudo rm -rf "$yaruDir"
  elif [[ "$1" != "setup" ]]; then
    echo "An unexpected error occured"
  fi
  echo ""; echo "----------------------------"; echo ""
  if [[ "$1" == "stock" ]]; then
    echo "    Installed stock yaru"
  elif [[ "$1" == "release" ]] || [[ "$1" == "unstable" ]]; then
    echo "        Updated yaru"
  elif [[ "$1" == "setup" ]]; then
    echo "    Yaru setup successful"
  fi
  echo ""; echo "----------------------------"
}

updatePackage() {
  echo "Updating package:"
  latestVer=$(curl -k -s https://api.github.com/repos/dragon8oy/mollusc-themes/releases/latest | grep "tag_name" | cut -d v -f 2,3 | tr -d \",)
  if [ "${latestVer//.}" -ne "${version//.}" ]; then
    echo "Program outdated, v$latestVer is available"
    installPackage
  else
    echo "Program up-to-date"
  fi
}

installPackage() {
  echo "Installing:"
  if [[ ! -d "/tmp/mollusc-themes" ]]; then
    sudo mkdir /tmp/mollusc-themes
  fi
  cd /tmp/mollusc-themes
  sudo curl --progress-bar -O -L $(curl -s -L https://api.github.com/repos/dragon8oy/mollusc-themes/releases/latest |grep "browser_download_url.*deb" |cut -d : -f 2,3 |tr -d \")
  if ! file mollusc-themes_all.deb | grep -q 'Debian binary package'; then
    echo "mollusc-themes_all.deb: Not a Debian package"
    echo "  ATTENTION: Downloaded update faulty"
    return
  fi
  sudo dpkg -i mollusc-themes_all.deb
  cd /tmp/; sudo rm -rf /tmp/mollusc-themes
  echo ""; echo "-----------------------------"; echo ""
  echo "       Updated package"
  echo ""; echo "----------------------------"
}

if [[ "$@" != "" ]]; then
  case $1 in
      -h|--help) echo "Mollusc-themes Copyright (C) 2020 Stuart Hayhurst"; 
echo "This program comes with ABSOLUTELY NO WARRANTY."; echo "This is free software; see the source for copying conditions."; echo ""; echo "Usage: update-themes [-OPTION]"; echo "Help:"; echo "-h | --help          : Display this help page"; echo "-u | --update        : Download updates to mollusc-themes"; echo "-y | --yaru [OPTION] : Downloads, installs or sets up yaru"; echo ""; echo "    stock    : Installs version of yaru bundled with mollusc-themes"; echo "    release  : Installs latest release of yaru"; echo "    unstable : Installs latest git version of yaru"; echo "    setup    : Sets yaru-dark as the shell, gtk, icon, sound and cursor theme"; echo ""; echo "Program written by: Dragon8oy"; exit;;
  -y|--yaru) updateYaru "$2"; exit;;
  -u|-p|--update|--package) updatePackage; exit;;
  *) echo "Unknown parameter passed: $1"; exit 1;;
  esac
else
    echo "No argument specified"
fi
