#!/bin/bash
nvidia-settings --assign "CurrentMetaMode=HDMI-0: nvidia-auto-select +0+0, DP-2: 1920x1080_75 +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On, AllowGSYNCCompatible=On}"
