#!/bin/bash
checkDeps() {
  if [[ "$1" == "stable" ]]; then #Check for unzip or tar if installing stable
    if ! command -v unzip > /dev/null 2>&1 && ! command -v tar > /dev/null 2>&1; then
      echo "Both, unzip and tar are missing, one required"
      depMissing="true"
    fi
  fi
  if ! command -v gsettings > /dev/null 2>&1; then #Check for dependencies to setup the themes
    echo "Gsettings missing"
    depMissing="true"
  fi
  if ! gsettings list-schemas |grep user-theme > /dev/null 2>&1; then
    echo -n "Searching for User Themes..."
    schemasPath=$(find / -iname 'gschemas.compiled' 2>&1 |grep -v "Permission denied" |grep user-theme@gnome-shell-extensions.gcampax.github.com)
    echo " Done"
    if [[ "$schemasPath" == "" ]]; then
      echo "User Themes extension missing"
      depMissing="true"
    fi
  fi

  if [[ "$1" == "unstable" ]] || [[ "$1" == "stable" ]]; then #Check for build dependencies
    if ! command -v grep > /dev/null 2>&1; then
      echo "Grep missing"
      depMissing="true"
    fi
    if ! command -v sed > /dev/null 2>&1; then
      echo "Sed missing"
      depMissing="true"
    fi
    if ! command -v make > /dev/null 2>&1; then
      echo "Make missing"
      depMissing="true"
    fi
    if ! git --version > /dev/null 2>&1; then
      echo "Git missing"
      depMissing="true"
    fi
    if ! command -v meson > /dev/null 2>&1; then
      echo "Meson missing"
      depMissing="true"
    fi
    if ! command -v sassc > /dev/null 2>&1; then
      echo "Sassc missing"
      depMissing="true"
    fi
    if [[ ! -d "/usr/include/gtk-3.0/" ]]; then
      echo "libgtk-3-dev missing"
      depMissing="true"
    fi
  fi

  if [[ "$depMissing" == "true" ]]; then
    echo "1 or more dependencies are missing, please install them and try again"
    exit 1
  fi
}

confirm() {
  read -r -p "$1" response
  if ! [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
    echo "Cancelled"
    exit
  fi
}

completedMessage() {
  if [[ "$1" == "install" ]]; then
    echo -e "----------------------------\n"
    echo -e "   Themes update complete\n"
    echo "----------------------------"
  elif [[ "$1" == "setup" ]]; then
    echo -e "---------------------------\n"
    echo -e "   Themes setup complete\n"
    echo "---------------------------"
  fi
}

setupThemes() {
  if gsettings list-schemas |grep user-theme > /dev/null 2>&1; then
    gsettings set org.gnome.shell.extensions.user-theme name Yaru-dark
  else
    schemasPath=$(find / -iname 'gschemas.compiled' 2>&1 |grep -v "Permission denied" |grep user-theme@gnome-shell-extensions.gcampax.github.com)
    if [[ "$schemasPath" == "" ]]; then
      echo "User-themes not installed correctly, or an error occured"
      return
    fi
    gsettings --schemadir "${schemasPath///gschemas.compiled}" set org.gnome.shell.extensions.user-theme name Yaru-dark
  fi
  gsettings set org.gnome.desktop.interface gtk-theme Yaru-dark
  gsettings set org.gnome.desktop.interface icon-theme Argon
  gsettings set org.gnome.desktop.sound theme-name Yaru
  gsettings set org.gnome.desktop.interface cursor-theme Yaru
}

prepareBuild() {
  if [[ -d "/tmp/update-themes" ]] && [[ ! -w "/tmp/update-themes" ]]; then
    echo "/tmp/update-themes is unwritable"
    exit
  else
    mkdir -p /tmp/update-themes; cd /tmp/update-themes || exit 1
  fi
}

cleanBuild() {
  cd /tmp || exit 1
  sudo rm -rf /tmp/update-themes
}

updateYaru() {
  prepareBuild
  if [[ "$1" == "unstable" ]]; then
    buildDir="yaru"
    git clone --depth 1 https://github.com/ubuntu/yaru.git
  elif [[ "$1" == "stable" ]]; then
    latestVersion="$(git ls-remote --refs --tags --sort="v:refname" https://github.com/ubuntu/yaru.git |grep -v "tags/r[0-9]" |tail -n1)"
    latestVersion="${latestVersion##*tags/}"

    downloadUrl="https://github.com/ubuntu/yaru/archive/$latestVersion"
    if command -v tar > /dev/null 2>&1; then
      extractCommand="tar -xf $latestVersion.tar.gz"
      downloadUrl="$downloadUrl.tar.gz"
    elif command -v unzip > /dev/null 2>&1; then
      extractCommand="unzip $latestVersion.zip"
      downloadUrl="$downloadUrl.zip"
    fi
    curl --progress-bar -O -L "$downloadUrl"
    $extractCommand

    rm "$latestVersion".*
    buildDir="yaru-$latestVersion"
  fi
  if [[ -d "/tmp/update-themes/$buildDir" ]]; then
    cd "$buildDir" || exit 1
    sudo rm -rf /usr/share/themes/Yaru*
    sudo ./bootstrap.sh -b
  fi
}

updateArgonIcons() {
  prepareBuild
  if [[ "$1" == "unstable" ]]; then
    buildDir="argon-icon-theme"
    git clone --depth 1 https://github.com/Dragon8oy/argon-icon-theme.git
  elif [[ "$1" == "stable" ]]; then
    latestVersion="$(git ls-remote --refs --tags --sort="v:refname" https://github.com/Dragon8oy/argon-icon-theme.git |tail -n1)"
    latestVersion="${latestVersion##*tags/}"

    downloadUrl="https://github.com/Dragon8oy/argon-icon-theme/archive/$latestVersion"
    if command -v tar > /dev/null 2>&1; then
      extractCommand="tar -xf $latestVersion.tar.gz"
      downloadUrl="$downloadUrl.tar.gz"
    elif command -v unzip > /dev/null 2>&1; then
      extractCommand="unzip $latestVersion.zip"
      downloadUrl="$downloadUrl.zip"
    fi
    curl --progress-bar -O -L "$downloadUrl"
    $extractCommand

    rm "$latestVersion".*
    buildDir="argon-icon-theme-${latestVersion/v}"
  fi
  if [[ -d "/tmp/update-themes/$buildDir" ]]; then
    cd "$buildDir" || exit 1
    sudo make uninstall
    make index
    sudo make install; sudo make refresh
  fi
}

updateArgonGrub() {
  prepareBuild
  if [[ "$1" == "unstable" ]]; then
    buildDir="argon-grub-theme"
    git clone --depth 1 https://github.com/Dragon8oy/argon-grub-theme.git
  elif [[ "$1" == "stable" ]]; then
    latestVersion="$(git ls-remote --refs --tags --sort="v:refname" https://github.com/Dragon8oy/argon-grub-theme.git |tail -n1)"
    latestVersion="${latestVersion##*tags/}"

    downloadUrl="https://github.com/Dragon8oy/argon-grub-theme/archive/$latestVersion"
    if command -v tar > /dev/null 2>&1; then
      extractCommand="tar -xf $latestVersion.tar.gz"
      downloadUrl="$downloadUrl.tar.gz"
    elif command -v unzip > /dev/null 2>&1; then
      extractCommand="unzip $latestVersion.zip"
      downloadUrl="$downloadUrl.zip"
    fi
    curl --progress-bar -O -L "$downloadUrl"
    $extractCommand

    rm "$latestVersion".*
    buildDir="argon-grub-theme-$latestVersion"
  fi
  if [[ -d "/tmp/update-themes/$buildDir" ]]; then
    cd "$buildDir" || exit 1
    sudo ./install.sh --install --background Night.png --resolution 1080p
  fi
}

updateRainbow() {
  prepareBuild
  if [[ "$1" == "unstable" ]]; then
    buildDir="rainbow-cursor"
    git clone --depth 1 https://github.com/Dragon8oy/rainbow-cursor.git
  elif [[ "$1" == "stable" ]]; then
    latestVersion="$(git ls-remote --refs --tags --sort="v:refname" https://github.com/Dragon8oy/rainbow-cursor.git |tail -n1)"
    latestVersion="${latestVersion##*tags/}"

    downloadUrl="https://github.com/Dragon8oy/rainbow-cursor/archive/$latestVersion"
    if command -v tar > /dev/null 2>&1; then
      extractCommand="tar -xf $latestVersion.tar.gz"
      downloadUrl="$downloadUrl.tar.gz"
    elif command -v unzip > /dev/null 2>&1; then
      extractCommand="unzip $latestVersion.zip"
      downloadUrl="$downloadUrl.zip"
    fi
    curl --progress-bar -O -L "$downloadUrl"
    $extractCommand

    rm "$latestVersion".*
    buildDir="rainbow-cursor-${latestVersion/v}"
  fi
  if [[ -d "/tmp/update-themes/$buildDir" ]]; then
    cd "$buildDir" || exit 1
    sudo mkdir -p /usr/share/rainbow-cursor
    sudo cp rainbow-cursor.sh /usr/share/rainbow-cursor
    sudo cp launch-cursor.sh /usr/share/rainbow-cursor
    if [[ "$USER" == "root" ]] || [[ "$USER" == "" ]]; then
      read -r -p "Are you sure you want to install rainbow-cursor as root? [y/N] (Only root will see the cursor) " response
      if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
        installPath="/root/.bashrc"
      else
        read -r -p "Do you want to install as a different user instead? [y/N] " response
        if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
          echo "Enter the name of the user to install for:"
          read -r targetUser
          installPath="/home/$targetUser/.bashrc"
        else
          return
        fi
      fi
    else
      installPath="/home/$USER/.bashrc"
    fi
    if [[ -f "$installPath" ]]; then
      if grep -q "/usr/share/rainbow-cursor/" "$installPath"; then
        return
      else
        echo "#Add rainbow cursor" >> "$installPath"
        echo ". /usr/share/rainbow-cursor/launch-cursor.sh" >> "$installPath"
      fi
    else
      echo "Couldn't find \"$installPath\""
    fi
  fi
}

updateThemes() {
  if [[ "$1" == "unstable" ]]; then
    confirm "Themes will be updated to unstable versions. Are you sure? [y/N] "
  fi
  checkDeps "$1"
  updateArgonGrub "$1"
  updateYaru "$1"
  updateArgonIcons "$1"
  cleanBuild
  setupThemes
  completedMessage "install"
}

if [[ "$1" != "" ]]; then
  case $1 in
    -h|--help) echo "Usage: update-themes [-OPTION]"; \
    echo "Help:"; \
    echo "-h | --help                 : Display this help page"; \
    echo "-u | --unstable             : Update themes to latest unstable versions"; \
    echo "-s | --stable               : Update themes to latest stable versions"; \
    echo "Program written by: Dragon8oy"; exit;;
  -u|--unstable) updateThemes "unstable"; exit;;
  -i|--install|--stable) updateThemes "stable"; exit;;
  -r|--rainbow) updateRainbow "unstable"; cleanBuild; exit;;
  *) echo "Unknown parameter passed: $1"; exit 1;;
  esac
else
  echo "No argument specified"
  "$(dirname "${BASH_SOURCE[0]}")/update-themes" "--help"
fi
