#!/bin/bash
checkDeps() {
  if [[ "$1" == "stable" ]]; then #Check for unzip or tar if installing stable
    if ! command -v unzip > /dev/null 2>&1 && ! command -v tar > /dev/null 2>&1; then
      echo "Both, unzip and tar are missing, one required"
      depMissing="true"
    fi
  fi
  if ! command -v gsettings > /dev/null 2>&1; then #Check for dependencies to setup the themes
    echo "Gsettings missing"
    depMissing="true"
  fi
  if ! gsettings list-schemas |grep user-theme > /dev/null 2>&1; then
    echo -n "Searching for User Themes..."
    schemasPath=$(find / -iname 'gschemas.compiled' 2>&1 |grep -v "Permission denied" |grep user-theme@gnome-shell-extensions.gcampax.github.com)
    echo " Done"
    if [[ "$schemasPath" == "" ]]; then
      echo "User Themes extension missing"
      depMissing="true"
    fi
  fi

  if [[ "$1" == "unstable" ]] || [[ "$1" == "stable" ]]; then #Check for build dependencies
    for dependency in "grep" "sed" "make" "git" "meson" "sassc"; do
      if ! command -v "$dependency" > /dev/null 2>&1; then
        echo "${dependency^} missing"
        depMissing="true"
      fi
    done
    if [[ ! -d "/usr/include/gtk-3.0/" ]]; then
      echo "libgtk-3-dev missing"
      depMissing="true"
    fi
  fi

  if [[ "$depMissing" == "true" ]]; then
    echo "1 or more dependencies are missing, please install them and try again"
    exit 1
  fi
}

confirm() {
  read -r -p "$1" response
  if ! [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
    echo "Cancelled"
    exit
  fi
}

completedMessage() {
  if [[ "$1" == "install" ]]; then
    echo -e "----------------------------\n"
    echo -e "   Themes update complete\n"
    echo "----------------------------"
  elif [[ "$1" == "setup" ]]; then
    echo -e "---------------------------\n"
    echo -e "   Themes setup complete\n"
    echo "---------------------------"
  fi
}

setupThemes() {
  if gsettings list-schemas |grep user-theme > /dev/null 2>&1; then
    gsettings set org.gnome.shell.extensions.user-theme name Yaru
  else
    schemasPath=$(find / -iname 'gschemas.compiled' 2>&1 |grep -v "Permission denied" |grep user-theme@gnome-shell-extensions.gcampax.github.com)
    if [[ "$schemasPath" == "" ]]; then
      echo "User-themes not installed correctly, or an error occured"
      return
    fi
    gsettings --schemadir "${schemasPath///gschemas.compiled}" set org.gnome.shell.extensions.user-theme name Yaru
  fi
  gsettings set org.gnome.desktop.interface gtk-theme Yaru-dark
  gsettings set org.gnome.desktop.interface icon-theme Argon
  gsettings set org.gnome.desktop.sound theme-name Yaru
  gsettings set org.gnome.desktop.interface cursor-theme Yaru
}

prepareBuild() {
  if [[ -d "/tmp/update-themes" ]] && [[ ! -w "/tmp/update-themes" ]]; then
    echo "/tmp/update-themes is unwritable"
    exit
  else
    mkdir -p /tmp/update-themes; cd /tmp/update-themes || exit 1
  fi
}

cleanBuild() {
  cd /tmp || exit 1
  sudo rm -rf /tmp/update-themes
}

updateComponent() { #buildDir #projectUrl #projectInstallCommand
  prepareBuild
  release="$1"
  projectName="$2"
  projectUrl="$3"
  projectInstallCommand="$4"
  if [[ "$release" == "unstable" ]]; then
    buildDir="$projectName"
    git clone --depth 1 "$projectUrl.git"
  elif [[ "$1" == "stable" ]]; then
    latestVersion="$(git ls-remote --refs --tags --sort="v:refname" "$projectUrl.git" |grep -v "tags/r[0-9]" |tail -n1)"
    latestVersion="${latestVersion##*tags/}"

    downloadUrl="$projectUrl/archive/$latestVersion"
    if command -v tar > /dev/null 2>&1; then
      extractCommand="tar -xf $latestVersion.tar.gz"
      downloadUrl="$downloadUrl.tar.gz"
    elif command -v unzip > /dev/null 2>&1; then
      extractCommand="unzip $latestVersion.zip"
      downloadUrl="$downloadUrl.zip"
    fi
    curl --progress-bar -O -L "$downloadUrl"
    $extractCommand

    rm "$latestVersion".*
    buildDir="$projectName-${latestVersion/v}"
  fi
  if [[ -d "/tmp/update-themes/$buildDir" ]]; then
    cd "$buildDir" || exit 1
    $projectInstallCommand "$buildDir"
  fi
}

installYaru() {
  sudo rm -rf /usr/share/themes/Yaru*
  sudo ./bootstrap.sh -b
}

installArgonIcons() {
  sudo make uninstall
  make index
  sudo make install; sudo make refresh
}

installArgonGrub() {
  sudo ./install.sh --install --background Crystals.png --resolution 1080p --fontcolour "#cccccc,#ffffff" --fontsize 24 --font Terminus.ttf --bold --auto
}

updateThemes() {
  if [[ "$1" == "unstable" ]]; then
    confirm "Themes will be updated to unstable versions. Are you sure? [y/N] "
  fi
  checkDeps "$1"
  updateComponent "$1" "yaru" "https://github.com/ubuntu/yaru" "installYaru"
  updateComponent "$1" "argon-icon-theme" "https://github.com/Dragon8oy/argon-icon-theme" "installArgonIcons"
  updateComponent "$1" "argon-grub-theme" "https://github.com/Dragon8oy/argon-grub-theme" "installArgonGrub"
  cleanBuild
  setupThemes
  completedMessage "install"
}

if [[ "$1" != "" ]]; then
  case $1 in
    -h|--help) echo "Usage: update-themes [-OPTION]"; \
    echo "Help:"; \
    echo "-h | --help                 : Display this help page"; \
    echo "-u | --unstable             : Update themes to latest unstable versions"; \
    echo "-s | --stable               : Update themes to latest stable versions"; \
    echo "Program written by: Dragon8oy"; exit;;
  -u|--unstable) updateThemes "unstable"; exit;;
  -i|--install|-s|--stable) updateThemes "stable"; exit;;
  *) echo "Unknown parameter passed: $1"; exit 1;;
  esac
else
  echo "No argument specified"
  "$(dirname "${BASH_SOURCE[0]}")/update-themes" "--help"
fi
