#!/bin/bash

#Set terminal profile
#dconf load /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/ < /usr/share/mollusc-themes/terminal-profile.dconf

#Set wallpapers
gsettings set org.gnome.desktop.screensaver picture-uri file:///usr/share/mollusc-themes/LockScreenWallpaper.jpg
gsettings set org.gnome.desktop.background picture-uri file:///usr/share/mollusc-themes/DesktopWallpaper.jpg

gsettings set org.gnome.desktop.background picture-options zoom
gsettings set org.gnome.desktop.background primary-color 000000
gsettings set org.gnome.desktop.background secondary-color 000000

#Set plymouth theme
update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/linux-mac-plymouth/linux-mac-plymouth.plymouth 100
update-alternatives --config default.plymouth
plymouth-set-default-theme linux-mac-plymouth

update-initramfs -u -k all

echo "Successfully installed"
echo "For nvidia systems, you may want to apply the following:"
echo "  - Set 'GRUB_GFXMODE' to your resolution in '/etc/default/grub'" 
echo "  - Add 'quiet splash nvidia-drm.modeset=1' to 'GRUB_CMDLINE_LINUX_DEFAULT'"
echo "  - Run 'sudo update-initramfs -u -k all'"
